#!/usr/bin/env bash
# Rebuild/verify the encapsulated `modules` branch (sharing module, stack PR #3).
#
# The branch = sharing_tab (PR #2 tip) + overlay (see overlay_commits.txt):
# one GENERATED move commit (@TRANSFORM, from move_map.tsv) plus hand-authored
# commits cherry-picked by exact subject.
#
# `transform` regenerates the move commit deterministically (git mv +
# quote-anchored path rewrites), so when sharing_tab moves under review,
# `rebuild` replays the branch and conflicts can only appear in the small
# hand-authored overlay — never in the ~100-file move commit.
#
# INVARIANT: move_map.tsv targets must match the paths the overlay commits
# create and reference (modules/sharing/). Retargeting the map without
# rewriting every overlay commit breaks every cherry-pick after the transform.
#
# Called by: just bar::sharing-module <transform|rebuild|verify|status|publish>
set -euo pipefail

DEVTOOLS_DIR="${DEVTOOLS_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."; pwd)}"
BAR="${BAR_DIR:-${DEVTOOLS_DIR}/Beyond-All-Reason}"
SELF_DIR="${DEVTOOLS_DIR}/scripts/sharing-module"

TIP="${SHARING_TIP:-sharing_tab}"
BRANCH="${MODULES_BRANCH:-modules}"
MOVE_MAP="${SELF_DIR}/move_map.tsv"
OVERLAY="${SELF_DIR}/overlay_commits.txt"
MOVE_COMMIT_SUBJECT="modules: relocate sharing stack into modules/sharing"

step() { printf '\033[1;34m▸ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
err()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*" >&2; }

git_bar() { git -C "$BAR" -c submodule.recurse=false "$@"; }

# Locate the worktree that has $BRANCH checked out.
# (awk must consume all input — an early exit SIGPIPEs git under pipefail)
modules_worktree() {
    git_bar worktree list --porcelain | awk -v want="refs/heads/${BRANCH}" '
        /^worktree /  { wt = substr($0, 10) }
        /^branch /    { if (substr($0, 8) == want && !found) { found = wt } }
        END           { if (found) print found }'
}

# Worktree auto-provisioned when no checkout of $BRANCH exists. Convention:
# worktrees live visibly in ~/code (Daniel's), never hidden inside repos.
WT_HOME="${MODULES_WT_HOME:-${HOME}/code/modules}"

require_worktree() {
    WT="$(modules_worktree)"
    if [[ -z "$WT" ]]; then
        step "No worktree has '${BRANCH}' checked out — provisioning ${WT_HOME}"
        git_bar worktree add "$WT_HOME" "$BRANCH" >/dev/null
        WT="$WT_HOME"
    fi
    # dev-env for typecheck/specs (idempotent): engine type stubs + lux test deps
    git -C "$WT" -c submodule.recurse=false submodule update --init recoil-lua-library >/dev/null 2>&1 || true
    [[ -e "$WT/.lux" ]] || ln -sfn "${BAR}/.lux" "$WT/.lux"
}

git_wt() { git -C "$WT" -c submodule.recurse=false "$@"; }

map_rows() { grep -v '^\s*#' "$MOVE_MAP" | grep -v '^\s*$'; }

# ── transform: generate the move commit on the current HEAD ──────────────────
apply_moves() {
    while IFS=$'\t' read -r old new; do
        local src="${old%/}" dst="${new%/}"
        if [[ ! -e "$WT/$src" ]]; then
            err "Move source missing: $src (sharing_tab moved it? update move_map.tsv)"
            exit 1
        fi
        mkdir -p "$WT/$(dirname "$dst")"
        git_wt mv "$src" "$dst"
    done < <(map_rows)
}

# Rewrite quoted path references ("old..." / 'old...') for every map row.
apply_rewrites() {
    local sedscript
    sedscript="$(mktemp)"
    # LHS: escape regex dots; anchor on an opening quote so bare words like
    # sharing_modes/ or Modes/ never match. RHS paths contain no sed specials.
    map_rows | awk -F'\t' '{
        old = $1; gsub(/\./, "\\.", old)
        printf "s|([\"'\''])%s|\\1%s|g\n", old, $2
    }' > "$sedscript"
    ( cd "$WT" && git ls-files -z -- '*.lua' '*.md' '*.yml' '*.yaml' '*.json' '.busted' \
        | xargs -0 -r sed -E -i -f "$sedscript" )
    rm -f "$sedscript"
}

# Busted discovers module-local specs too.
apply_busted_root() {
    sed -i 's|ROOT = { "spec/" }|ROOT = { "spec/", "modules/sharing/spec/" }|g' "$WT/.busted"
    if ! grep -q 'modules/sharing/spec/' "$WT/.busted"; then
        err ".busted ROOT edit did not apply — check its formatting"
        exit 1
    fi
}

transform() {
    require_worktree
    step "Generating move commit on $(git_wt rev-parse --short HEAD) (${BRANCH})"
    apply_moves
    apply_rewrites
    apply_busted_root
    # -u, not -A: everything transform touches is tracked; never sweep up
    # untracked dev-env files (.lux symlink etc.)
    git_wt add -u
    git_wt commit -q -m "${MOVE_COMMIT_SUBJECT}

Generated by BAR-Devtools scripts/sharing-module/generate.sh from
move_map.tsv: git mv + quote-anchored include-path rewrites, plus the
.busted ROOT addition for module-local specs. No logic changes.

Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>"
    ok "Move commit created: $(git_wt rev-parse --short HEAD)"
}

# ── rebuild: replay the whole branch on the current $TIP ─────────────────────
rebuild() {
    require_worktree
    if ! git_wt diff --quiet || ! git_wt diff --cached --quiet; then
        err "Worktree ${WT} is dirty; commit or stash first."
        exit 1
    fi

    # Resolve overlay commits by exact subject on the previous branch tip.
    local -a plan=()
    while IFS= read -r line; do
        [[ "$line" =~ ^\s*# || -z "$line" ]] && continue
        if [[ "$line" == "@TRANSFORM" ]]; then
            plan+=("@TRANSFORM")
            continue
        fi
        local hash
        hash="$(git_bar log --format='%H%x09%s' "$BRANCH" -- | awk -F'\t' -v s="$line" '$2==s && !found {found=$1} END{if (found) print found}')"
        if [[ -z "$hash" ]]; then
            err "Overlay commit not found on ${BRANCH}: $line"
            exit 1
        fi
        # dev-env symlink must never ride in a commit (bites cherry-picks on
        # worktrees with the untracked symlink; has happened three times)
        if git_bar ls-tree "$hash" .lux | grep -q .lux; then
            err "Overlay commit contains .lux (git add -A strikes again): $line"
            err "Scrub it (git rm --cached .lux + amend) before rebuilding."
            exit 1
        fi
        plan+=("$hash")
    done < "$OVERLAY"

    step "Resetting ${BRANCH} to ${TIP} ($(git_bar rev-parse --short "$TIP"))"
    git_wt reset --hard "$TIP"

    for item in "${plan[@]}"; do
        if [[ "$item" == "@TRANSFORM" ]]; then
            transform
        else
            step "Cherry-picking $(git_bar log -1 --format='%h %s' "$item")"
            if ! git_wt cherry-pick "$item"; then
                err "Cherry-pick conflict — resolve in ${WT}, 'git cherry-pick --continue',"
                err "then re-run: just bar::sharing-module verify"
                exit 1
            fi
        fi
    done
    ok "Rebuilt ${BRANCH} on ${TIP}: $(git_wt log --oneline "${TIP}..HEAD" -- | wc -l) commits"
    git_wt log --oneline "${TIP}..HEAD" --
}

# ── verify: stale paths, type check, specs ───────────────────────────────────
verify() {
    require_worktree
    local fail=0

    step "Checking for stale pre-move paths"
    local pattern
    pattern="$(map_rows | awk -F'\t' '{old=$1; gsub(/\./,"\\.",old); printf "%s[\"'\'']%s", (NR>1?"|":""), old}')"
    if ( cd "$WT" && git grep -nE -- "$pattern" -- '*.lua' '*.md' '*.yml' '*.yaml' '*.json' '.busted' ); then
        err "Stale references to moved paths (above)"
        fail=1
    else
        ok "No stale path references"
    fi

    step "Type check (emmylua_check, errors only)"
    # Pre-existing baseline on sharing_tab (gui_pip.lua gameFrame). Re-baseline
    # when the stack rebases: SHARING_TYPE_ERROR_BASELINE=<n>.
    local baseline="${SHARING_TYPE_ERROR_BASELINE:-1}"
    local json count
    json="$( (cd "$WT" && emmylua_check -c .emmyrc.json -f json . 2>/dev/null) || true)"
    count="$(printf '%s\n' "$json" | jq '[.[] | .diagnostics[] | select(.severity == 1)] | length')"
    if [[ "$count" -gt "$baseline" ]]; then
        { printf '%s\n' "$json" | jq -r '.[] | . as $f | .diagnostics[] | select(.severity == 1) |
            "\($f.file):\(.range.start.line + 1): \(.code): \(.message)"' | head -40; } || true
        err "$count type error(s) (baseline: $baseline)"
        fail=1
    else
        ok "No type errors beyond baseline ($count/$baseline)"
    fi

    step "Unit specs (busted via lx)"
    if (cd "$WT" && lx --lua-version 5.1 test); then
        ok "Specs green"
    else
        err "Specs failed (missing deps? run: cd ${WT} && lx --lua-version 5.1 sync)"
        fail=1
    fi

    [[ "$fail" -eq 0 ]] && ok "verify passed" || { err "verify failed"; exit 1; }
}

status() {
    require_worktree
    step "${BRANCH} @ ${WT}"
    git_wt log --oneline "${TIP}..${BRANCH}" -- || true
    if git_bar merge-base --is-ancestor "$TIP" "$BRANCH"; then
        ok "${BRANCH} contains ${TIP} ($(git_bar rev-parse --short "$TIP"))"
    else
        warn "${BRANCH} is NOT on top of ${TIP} — run: just bar::sharing-module rebuild"
    fi
}

# ── publish: push the branch to the fork and open/update the draft PR ────────
publish() {
    require_worktree
    if [[ -e "$(git_wt rev-parse --git-dir)/CHERRY_PICK_HEAD" ]]; then
        err "A cherry-pick is in progress in ${WT} — never publish a mid-rebuild state."
        exit 1
    fi
    local fork_owner
    fork_owner="$(git_bar remote get-url origin 2>/dev/null | sed -n 's|.*[:/]\([^/]*\)/.*|\1|p')"
    local upstream_repo="${UPSTREAM_REPO:-beyond-all-reason/Beyond-All-Reason}"
    local pr_base="${MODULES_PR_BASE:-sharing/05-game-modes-export}"
    # Body = generated header + Daniel's manual description (verbatim, never
    # LLM-edited) + generated summary — same convention as sharing-split's
    # descriptions/ directory.
    local body
    body="$(mktemp)"
    cat "${SELF_DIR}/pr_header.md" <(echo) "${SELF_DIR}/description.md" <(echo) "${SELF_DIR}/pr_summary.md" > "$body"

    # The PR's base is the split's top leaf; its commits are SYNTHESIZED, so
    # GitHub's merge-base only collapses the diff if the leaf is an ancestor
    # of HEAD. Publish-facing rebuilds must therefore run:
    #   SHARING_TIP=upstream/sharing/05-game-modes-export just bar::sharing-module rebuild
    local leaf="upstream/sharing/05-game-modes-export"
    if git_wt rev-parse --verify -q "$leaf" >/dev/null 2>&1 && ! git_wt merge-base --is-ancestor "$leaf" HEAD; then
        warn "$leaf is not an ancestor of HEAD — the PR will show the whole #5704 stack."
        warn "Rebuild first: SHARING_TIP=$leaf just bar::sharing-module rebuild"
    fi

    step "Pushing ${BRANCH} to origin (${fork_owner})"
    git_wt push origin "HEAD:refs/heads/${BRANCH}" --force-with-lease
    ok "Pushed"

    local existing
    # NB: gh pr list --head "owner:branch" does not match cross-fork PRs;
    # filter on headRepositoryOwner explicitly.
    existing="$(gh pr list --repo "$upstream_repo" --state open \
        --json number,headRefName,headRepositoryOwner \
        --jq ".[] | select(.headRefName == \"${BRANCH}\" and .headRepositoryOwner.login == \"${fork_owner}\") | .number" 2>/dev/null | head -1 || true)"
    if [[ -n "$existing" && "$existing" != "null" ]]; then
        step "Updating body of existing PR #${existing}"
        gh pr edit "$existing" --repo "$upstream_repo" --body-file "$body"
        ok "PR #${existing} updated: https://github.com/${upstream_repo}/pull/${existing}"
    else
        step "Opening draft PR (${fork_owner}:${BRANCH} -> ${pr_base})"
        gh pr create --repo "$upstream_repo" --draft \
            --head "${fork_owner}:${BRANCH}" --base "$pr_base" \
            --title "The Modules Format" --body-file "$body"
        ok "Draft PR opened"
    fi
}

usage() {
    sed -n '2,16p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
    exit 1
}

cmd="${1:-}"
shift || true
case "$cmd" in
    transform) transform "$@" ;;
    rebuild)   rebuild "$@" ;;
    verify)
        # emmylua_check/lx live in the distrobox when one is configured.
        source "${DEVTOOLS_DIR}/scripts/common.sh"
        enter_distrobox verify
        verify "$@"
        ;;
    status)    status "$@" ;;
    publish)   publish "$@" ;;
    *)         usage ;;
esac
